language: groovy
before_script: ./bin/ci/before_script.sh
script: ./gradlew check --info
notifications:
  email: michael@rabbitmq.com
services:
  - rabbitmq
branches:
  only:
    - master
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
